name: CI for Udemy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable TS
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -Name "RemoteDesktop-UserMode-In-TCP"
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Set up the Udemy Downloader and Download Courses
        run: |
          cd C:\
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
          git clone https://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@github.com/msftvu/udemy-downloader.git
          New-Item -ItemType Directory -Path ".\udemy-downloader\dependencies" -Force
          (New-Object System.Net.WebClient).DownloadFile("https://github.com/shaka-project/shaka-packager/releases/download/v3.2.0/packager-win-x64.exe", "C:\udemy-downloader\dependencies\shaka-packager.exe")
          (New-Object System.Net.WebClient).DownloadFile("https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip", "C:\ffmpeg-master-latest-win64-gpl.zip")
          Expand-Archive -Path ".\ffmpeg-master-latest-win64-gpl.zip" -DestinationPath ".\udemy-downloader\dependencies" -Force
          Remove-Item -Path ".\ffmpeg-master-latest-win64-gpl.zip"
          (New-Object System.Net.WebClient).DownloadFile("https://github.com/aria2/aria2/releases/download/release-1.37.0/aria2-1.37.0-win-64bit-build1.zip", "C:\aria2-1.37.0-win-64bit-build1.zip")
          Expand-Archive -Path ".\aria2-1.37.0-win-64bit-build1.zip" -DestinationPath ".\udemy-downloader\dependencies" -Force
          Remove-Item -Path ".\aria2-1.37.0-win-64bit-build1.zip"
          $path = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
          $path += ";C:\udemy-downloader\dependencies"
          $path += ";C:\udemy-downloader\dependencies\ffmpeg-master-latest-win64-gpl\bin"          
          $path += ";C:\udemy-downloader\dependencies\aria2-1.37.0-win-64bit-build1"
          [System.Environment]::SetEnvironmentVariable("Path", $path, "Machine")
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
          $requirements = @"
          browser_cookie3
          m3u8
          requests
          yt-dlp
          bs4
          coloredlogs
          python-dotenv
          pathvalidate
          tqdm
          bitstring
          six
          protobuf
          webvtt-py
          pysrt
          lxml
          xmltodict
          demoji
          "@
          $requirements | Out-File -FilePath ".\udemy-downloader\requirements2.txt"
          python -m pip install -r ".\udemy-downloader\requirements2.txt"

      - name: Install ngrok using Chocolatey
        run: choco install ngrok -y
        
      - name: Authenticate with ngrok using the provided token
        run: ngrok authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          
      - name: Setup ngrok region
        run: |
          Add-Content -Path "${env:USERPROFILE}\AppData\Local\ngrok\ngrok.yml" -Value "region: us-cal-1"
          
      - name: Start an ngrok tunnel for port 3389
        run: ngrok tcp 3389
